[package]
name = "trade_protocal_lite"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bytes = { workspace = true }
prost = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
