[package]
name = "trade_protocal_lite"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bytes = "1.10.1"
prost = "0.13.5"
thiserror = "2.0.12"

[build-dependencies]
prost-build = "0.13.5"
