[package]
name = "tick_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
# Dependencies like redis, tokio might be added here
# redis = { workspace = true }
# tokio = { workspace = true }
# core_entities = { workspace = true } 