// This file is auto-generated by prost-build.
// It includes the Rust code generated from your .proto definitions.

// The module name here should match the package name defined in your .proto file
// or be a name you choose to namespace the generated code under.
// If your .proto file has `package trade_protocal_lite;`
// then the generated file will typically be `trade_protocal_lite.rs` inside OUT_DIR.

// We specified `out_dir("src/protos_generated")` in build.rs
// so prost_build will place the generated file trade_protocal_lite.rs (or similar)
// directly inside `src/protos_generated/`.

// Thus, we can directly include it.
// The actual name of the file will be derived from the package name in the .proto file.
// If `package trade_protocal_lite;` is used, then the file will be `trade_protocal_lite.rs`.
pub mod trade_protocal_lite {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/protos_generated/trade_protocal_lite.rs"));
}

// You can then re-export items if you wish, for easier access from other modules:
// pub use trade_protocal_lite::LoginRequest;
// pub use trade_protocal_lite::LoginResponse;
// ... and so on for other messages and enums. 