[package]
name = "core_entities"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }