# A股模拟交易系统配置文件示例
# 复制此文件为 config.yml 并根据需要修改

# 服务器配置
server:
  # 监听地址 - 生产环境建议使用 0.0.0.0:8080
  listen_addr: "127.0.0.1:8080"
  # 最大连接数 - 根据服务器性能调整
  max_connections: 10000
  # 消息最大尺寸（字节）- 1MB
  max_message_size: 1048576
  # 缓冲区大小（字节）- 8KB
  buffer_size: 8192
  # 心跳超时（秒）
  heartbeat_timeout_secs: 30

# 订单引擎配置
order_engine:
  # 订单通知channel的缓冲区大小 - 高频交易可增大
  order_notification_buffer_size: 10000
  # 匹配通知channel的缓冲区大小
  match_notification_buffer_size: 10000
  # 是否启用订单验证 - 生产环境建议开启
  enable_validation: true
  # 订单池清理间隔（秒）- 1小时
  cleanup_interval_seconds: 3600
  # 保留已完成订单的时间（小时）- 24小时
  retain_completed_orders_hours: 24

# 市场数据引擎配置
market_data_engine:
  # 交易日期（格式：YYYY-MM-DD）- 根据实际交易日调整
  trade_date: "2024-09-23"
  # 是否在启动时自动加载全市场数据 - 首次启动建议开启
  auto_load_all_market_data: true
  # 行情通知缓冲区大小
  notification_buffer_size: 1000
  # 请求响应缓冲区大小
  request_buffer_size: 100

# 数据库配置
database:
  # 数据库连接URL - 请根据实际数据库配置修改
  database_url: "mysql://username:password@localhost:3306/a_shares_real_history"
  # 最大连接数 - 根据数据库性能调整
  max_connections: 20
  # 连接超时时间（秒）
  connect_timeout_secs: 30

# 日志配置
logging:
  # 日志级别: trace, debug, info, warn, error
  level: "info"
  # 是否输出到控制台
  console: true
  # 是否输出到文件
  file: true
  # 日志文件路径
  file_path: "logs/app.log"
  # 是否启用 JSON 格式 - 便于日志分析工具处理
  json_format: false

# 环境变量覆盖示例:
# export SHARES_SIM__SERVER__LISTEN_ADDR="0.0.0.0:8080"
# export SHARES_SIM__DATABASE__MAX_CONNECTIONS="50"
# export SHARES_SIM__LOGGING__LEVEL="debug" 